### ISSUE TITLE
CodeStyle

### ISSUE THREAD

**Issue by Zarwlar** [prodderman/Slider#11]
У тебя есть tslint, но ты используешь js файлы, и скорее всего, из-за этого не видишь предупреждений о неверной расстановке пробелов. Нужно полностью перейти на typescript

**Comment by prodderman** [comment]
проблема была в неправильной конфигурации, пробелы и другие недочеты исправил. С вашего позволения я бы оставил js файл, так как он никаким образом не влияет на реализацию слайдера
