### ISSUE TITLE
Использование одной и той же переменой для разных целей

### ISSUE THREAD

**Issue by Gulyaev52** [prodderman/Slider#13]
https://github.com/prodderman/Slider/blob/a5859276485750abc3005224a8fa2f6c8c4dafcf/src/components/model/model.ts#L80

`
  public calcToWithStep(value: number): void {
    let result;

    if (!this.options.type || this.options.to_fixed) {
      return;
    }

    result = Math.round(( value - this.options.min ) / this.options.step) * this.options.step + this.options.min;
    result = this.inDaipason(result, this.options.from, this.options.max);

    if (result !== this.options.to) {
      this.options.to = result;
      this.triggers.toChanged.notify(this.options.to);
    }
  }
`

Никогда нельзя использовать одну и ту же переменную для разных вычислений. Тут у тебя используется result для 3 разных вещей. Нужно создать 3 переменных и дать им подходящие имена, потому что у тебя сейчас нужно самому выводить, что означает тот или иной результат вычислений. Например тут `result = Math.round(( value - this.options.min ) / this.options.step) * this.options.step + this.options.min;`

**Comment by prodderman** [comment]
высчитывается одно значение, просто в несколько этапов, или так тоже не должно быть?

**Comment by Gulyaev52** [comment]
но результат этого выражения `Math.round(( value - this.options.min ) / this.options.step) * this.options.step + this.options.min` и этого `this.inDaipason(result, this.options.from, this.options.max)` имеет разную смысловую нагрузку. По этому лучше каждой переменной дай осмысленное значение, а финальное вычисление ты уже можешь поместить в переменную result (но опять же, result это слишком абстрактно, лучше конкретнее).

**Comment by Gulyaev52** [comment]
Щас намного лучше стало, но пробегись по всему проекту и поищи схожие места на всякий случай
