### ISSUE TITLE
Сложный метод

### ISSUE THREAD

**Issue by Gulyaev52** [prodderman/Slider#14]
https://github.com/prodderman/Slider/blob/a5859276485750abc3005224a8fa2f6c8c4dafcf/src/components/controller/controller.ts#L32

очень сложно читается метод. Нужна декомпозиция. Обработчики может вынести в отдельные методы

**Comment by prodderman** [comment]
там даже логики нет, просто все функции вызываются

**Comment by Zarwlar** [comment]
Нужно разбить init на отдельные методы
Например (init | apply)Callbacks, действия которые в if else c isUpdate происходят (и что вообще за isUpdate, может быть isUpdated?), для методов с attach тоже отдельный метод, и последние два действия с вьхой тоже в отдельный метод.
Что такое vanillaslide? И в целом (vanilla)

**Comment by prodderman** [comment]
vanilla - название слайдера. vanillaslide и прочие это кастомные события

**Comment by Geksanit** [comment]
можно закрывать
