### ISSUE TITLE
Слишком абстрактное имя переменной

### ISSUE THREAD

**Issue by Gulyaev52** [prodderman/Slider#15]
https://github.com/prodderman/Slider/blob/a5859276485750abc3005224a8fa2f6c8c4dafcf/src/components/view/view.ts#L28

чё за handle? Назови более конкретно

**Comment by prodderman** [comment]
handle переводится ручка, разве сильно абстрактно?

**Comment by Gulyaev52** [comment]
handle - это у тебя ползунок слайдера? если да, то всё нормально) Я просто не внимательно посмотрел и думал, что это у тебя такой-то обработчик
