### ISSUE TITLE
Непонятное имя класса

### ISSUE THREAD

**Issue by Gulyaev52** [prodderman/Slider#19]
https://github.com/prodderman/Slider/blob/a5859276485750abc3005224a8fa2f6c8c4dafcf/src/index.html#L65

что за rc?

**Comment by prodderman** [comment]
это только для демонстрации, к слайдеру отношения не имеет

**Comment by Gulyaev52** [comment]
лучше весь код в проекте держи в нормальном состояние, даже тот, который только для демонстрации)
