### ISSUE TITLE
В некоторых интерфейсах все проперти необязательные 

### ISSUE THREAD

**Issue by Gulyaev52** [prodderman/Slider#20]
https://github.com/prodderman/Slider/blob/a5859276485750abc3005224a8fa2f6c8c4dafcf/src/namespace.ts#L1

Вот я прям не верю, что тут все проперти необязательные. Плюс я видел ещё как минимум один интерфейс, у которого то же самое. Проблема такого подхода в том, что не понятен контракт класса. Какой минимум свойств мне нужно предоставить, что бы начать работать с сущностью. А так как у тебя все свойства необязательные, мне приходится изучать весь интерфейс и возможно даже лезть в код, что бы понять, какие свойства я должен предоставить, что бы у меня ничего не поломалось при использование класса.

**Comment by prodderman** [comment]
я могу создать слайдер не передав ни одного свойства
`new Slider()`
говорил же вроде об этом

**Comment by Gulyaev52** [comment]
тогда нет проблем)
