### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by kinda-neat** [prodderman/Slider#26]
Опиши каким образом у тебя взаимодействуют слои приложения, сейчас у тебя очень неявный источник правды, его нужно локализовать в модели, только модель должна быть stateful
У каждого слоя должна быть своя зона ответственности
Еще настоятельно рекомендую прочесть данные статьи, обновить, расширить свои знания :)
https://addyosmani.com/largescalejavascript/
https://habrahabr.ru/post/321050/
https://habrahabr.ru/post/276593/

**Comment by Zarwlar** [comment]
Можешь объяснить подробно, как из физического значения пикселей происходит конвертация в значения слайдера? Конкретно, какой сценарий работы программы происходит при перемещении ползунка слайдера, и наоборот - что происходит, если значение слайдера присвоить из другого контрола.
Пояснение про другой контрол:
Например, попробуй добавить текстовый input на страницу, через который можно было бы регулировать значения слайдера, и наоборот, чтобы изменяющиеся значения слайдера изменялись и в input.

**Comment by prodderman** [comment]
В общем Вид, который реагирует на различные события (например на движение мыши при зажатой левой кнопкой над ползунком) и оповещает о том какой это ползунок и координаты мыши относительно начала слайдера. Контроллер слушает эти оповещения и на основе данных Вида (длинна слайдера, координаты мыши) и данных от модели (минимальное и максимальное значение) ковертирует в реальные значения и передает это в Модель. В Модели полученное значение корректируется на основе шага и диапазона. После модель оповещает, что значение поменялось. Контроллер, который так же слушает оповещения и от Модели, конвертирует реальное значение уже в проценты и передает в Вид. После чего слайдер частично перерисовывается.

**Comment by ValentinAlexandrovich** [comment]
Можешь объяснить с точки зрения MVC к какому слою ты бы обнес классы SliderConstructor, VanillaSlider и почему ты решил их вынести отдельно? А также где с твоей точки зрения должны хранится параметры для инициализации слайдера, и обработчики событий из index.js.
