### ISSUE TITLE
Именование переменных jQuery

### ISSUE THREAD

**Issue by chmnkh** [prodderman/Slider#27]
```
const create = $('.create');
const slide =$('.slide');
const start =$('.start');
const end =$('.end');
```
Все переменные, которые поддерживают jQuery API, должны начинаться со знака $. Это из стандартов.
Тут же попутно разберись с непонятными пробелами после оператора присваивания: они у тебя то есть, то их нет.

**Comment by Geksanit** [comment]
вынеси в объект(controls) селектить по классу и можно закрывать
