### ISSUE TITLE
Именование параметров функций

### ISSUE THREAD

**Issue by chmnkh** [prodderman/Slider#30]
```
onCreate: (e, d) => {
   create.addClass('active');
   clearTimeout(timeId);
   timeId = setTimeout(remove, 200);
}
```
Называй параметры так, чтобы прочитав их, было сразу понятно, что это такое. Чтобы понять, что такое d, мне пришлось погулять около минуты по разным файлам. Event до e тоже сокращать не стоит, пиши полностью.

**Comment by chmnkh** [comment]
У тебя, кстати, в этой функции e и d вообще не используются, так зачем их передавать?)

**Comment by prodderman** [comment]
вообще index.js для демо используется, я даже не пытался делать его правильно, но видимо придется сделать

**Comment by Geksanit** [comment]
можно закрывать
