### ISSUE TITLE
setRoot не должен быть внутри if

### ISSUE THREAD

**Issue by Zarwlar** [prodderman/Slider#32]
Сейчас у тебя внутри setRoot происходит проверка на валидность рут и после этого происходит присвоение, хотя само название setRoot подразумевает только присвоение. Таким образом, тебе нужно проверять валидность node перед вызовом setRoot внутри конструктора.

Название checkNode подразумевает, что ты проверяешь node на корректность, но в итоге он возвращает хтмл элемент, это не очевидно. Нужно или переименовать метод, или разбить его на метод, который будет чекать валидность, и метод, который будет присваивать значение

**Comment by Geksanit** [comment]
можно закрывать, данного метода уже нет
