### ISSUE TITLE
Переписать логику по изменению опций

### ISSUE THREAD

**Issue by Gulyaev52** [prodderman/Slider#6]
https://github.com/prodderman/Slider/blob/9db8c94b34077e8dedb49462eb7ccf0252ff3dae/src/slider.ts#L79

у тебя в каждом кейсе нужно проставлять update = true. Это очень сильно попахивает. Почему нельзя просто провести глубоков сравнение опций?

**Comment by prodderman** [comment]
Убрал где мог, но это для работы колбека на изменения
