### ISSUE TITLE
Исправить типы опций

### ISSUE THREAD

**Issue by Gulyaev52** [prodderman/Slider#7]
https://github.com/prodderman/Slider/blob/9db8c94b34077e8dedb49462eb7ccf0252ff3dae/src/slider.ts#L12

Почему у тебя много где number | string? ты же можешь выбрать только один тип, разве нет? И если ты выберешь один тип, то проверки ниже значительно упростяться

**Comment by prodderman** [comment]
Это сделано для работы из js
