### ISSUE TITLE
При использование двух ползунков у слайдера один наезжает на другого

### ISSUE THREAD

**Issue by Zarwlar** [prodderman/Slider#9]
В результате чего слайдер не получается двигать в одну из сторон. В какую именно - зависит от того, в какую сторону перед этим сдвигали ползунок
![slider_behavior](https://user-images.githubusercontent.com/26929933/35438543-84908b54-02c9-11e8-8ff1-a1034fae084a.gif)

**Comment by prodderman** [comment]
Это характерно для большинства подобных слайдеров, в таком случае можно нажать на пустое пространство справа или слева от ползунков, чтобы сдвинуть соответствующие ползунки
